# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ApimaticCalculator
  #  apimatic_calculator client class.
  class ApimaticCalculatorClient
    # Singleton access to simple_calculator controller.
    # @return [SimpleCalculatorController] Returns the controller instance.
    def simple_calculator
      SimpleCalculatorController.instance
    end

    # Returns the configuration class for easy access.
    # @return [Configuration] Returns the actual configuration class.
    def config
      Configuration
    end
  end
end
